version: '3.4'
services:
 backend:
    environment: 
        MONGO_U: ${MONGO_U}
        MONGO_P: ${MONGO_P}
        CON_STR: ${MONGO_P}
    container_name: "backend"
    image: "docker.pkg.github.com/al3xdiaz/coderatbest.com/backend:latest"
    build:
        context: .
        dockerfile: backend/dockerfile
    ports: 
        - "3000:3000"
    restart: always
    volumes: 
        - "./backend/server:/code/server"
        - "./backend/server.js:/code/server.js"